### ISSUE TITLE
Fix error when creating a new property

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/awsIoTThing#12]
DEBUG: undefined
c:\Localstuff\awsIoTThing\index.js:120
               Object.defineProperty(_this._local, propertyName, {
                      ^

TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (native)
    at awsIoTThing.reportProperty (c:\Localstuff\awsIoTThing\index.js:120:23)
    at Object.callback (c:\Localstuff\nodeIoTLauncher\index.js:35:47)
    at ThingShadowsClient.<anonymous> (c:\Localstuff\awsIoTThing\index.js:325:25)
    at emitMany (events.js:121:13)
    at ThingShadowsClient.emit (events.js:195:7)
    at ThingShadowsClient._handleMessages (c:\Localstuff\awsIoTThing\node_modules\aws-iot-device-sdk\thing\index.js:276:12)
    at DeviceClient.<anonymous> (c:\Localstuff\awsIoTThing\node_modules\aws-iot-device-sdk\thing\index.js:313:21)
    at emitThree (events.js:110:13)
    at DeviceClient.emit (events.js:188:7)

**Comment by joshn-ridewta-com** [comment]
Error was the result of calling setLocalToDesired prior.  Need to fix that bug.
